dev:
  stage: development
  branch: develop
  deploy_path: ~/www/dev
  hostname: 162.247.XXX.XXX
  user: avXXXXX

staging:
  stage: staging
  branch: master
  deploy_path: ~/www/staging
  hostname: 162.247.XXX.XXX
  user: avXXXXX

prod:
  stage: production
  branch: 0.1.0
  deploy_path: ~/www/prod
  hostname: 162.247.XXX.XXX
  user: avXXXXX
