field: 6e341ae4-c396-4762-ab24-8a224c3933aa
fieldLayouts:
  b43487d1-24a6-4b4c-84f8-64af136db66a:
    tabs:
      -
        elements:
          -
            fieldUid: b3acf43e-c97c-4003-8486-97694710feb9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b3acf43e-c97c-4003-8486-97694710feb9:
    contentColumnType: string
    fieldGroup: null
    handle: gridItem
    instructions: ''
    name: 'Grid Item'
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - cfb6ca95-87e7-4266-a266-9f5798b54a1d
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - e8615a95-6e04-431b-bf63-36acabd486d8
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - d2946ed8-0592-46cc-b6f3-650fae038509
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 4c6051b7-8ee0-4fe8-b531-18a995bf1864
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 793967a5-a62c-4699-9319-38b500e18ca5
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_2_griditem}}'
      fieldLayout: matrix
      maxRows: '4'
      minRows: '4'
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: curatedGrid
name: 'Curated Grid'
sortOrder: 1
