field: 6e341ae4-c396-4762-ab24-8a224c3933aa
fieldLayouts:
  4b7ed7c8-5560-4a0b-9e25-770d89c717ca:
    tabs:
      - fields:
          346d4aad-539f-4af8-8ab9-930fafbdc57e:
            required: true
            sortOrder: 1
          5e920a95-892a-4396-8dc8-357d877f3a75:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  346d4aad-539f-4af8-8ab9-930fafbdc57e:
    contentColumnType: text
    fieldGroup: null
    handle: headingText
    instructions: ''
    name: 'Heading Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  5e920a95-892a-4396-8dc8-357d877f3a75:
    contentColumnType: string
    fieldGroup: null
    handle: headingSize
    instructions: ''
    name: 'Heading Size'
    searchable: true
    settings:
      optgroups: true
      options:
        - __assoc__:
            - - label
              - H1
            - - value
              - h1
            - - default
              - ''
        - __assoc__:
            - - label
              - H2
            - - value
              - h2
            - - default
              - '1'
        - __assoc__:
            - - label
              - H3
            - - value
              - h3
            - - default
              - ''
        - __assoc__:
            - - label
              - H4
            - - value
              - h4
            - - default
              - ''
        - __assoc__:
            - - label
              - H5
            - - value
              - h5
            - - default
              - ''
        - __assoc__:
            - - label
              - H6
            - - value
              - h6
            - - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: headingBlock
name: 'Heading Block'
sortOrder: 2
