field: 6e341ae4-c396-4762-ab24-8a224c3933aa
fieldLayouts:
  7576ceb1-08aa-4b64-9d42-66155d73a17b:
    tabs:
      -
        elements:
          -
            fieldUid: 80da5ff3-0426-4efc-b528-d3b05bf6b844
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7c37af1a-f856-4e42-9bd7-d1c949d74cf2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 26843eac-36b8-4cf6-b0a3-40a0f9e9502f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  26843eac-36b8-4cf6-b0a3-40a0f9e9502f:
    contentColumnType: string
    fieldGroup: null
    handle: alignment
    instructions: ''
    name: Alignment
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - aligncenter
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - alignleft
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - alignright
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Full Width'
            -
              - value
              - alignfull
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  7c37af1a-f856-4e42-9bd7-d1c949d74cf2:
    contentColumnType: text
    fieldGroup: null
    handle: quoteAttribution
    instructions: ''
    name: 'Quote Attribution'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  80da5ff3-0426-4efc-b528-d3b05bf6b844:
    contentColumnType: text
    fieldGroup: null
    handle: quoteText
    instructions: ''
    name: 'Quote Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: pullQuoteBlock
name: 'Pull Quote Block'
sortOrder: 9
