field: 6e341ae4-c396-4762-ab24-8a224c3933aa
fieldLayouts:
  dd3471ea-87d1-4d0b-ac83-84072543563d:
    tabs:
      -
        elements:
          -
            fieldUid: 8a4a9188-8dad-4ea2-beda-79dca5d5b7c5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5a647dc5-6bc3-4530-8541-86caf15ef63a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 22b3b10f-5736-4552-967a-4610bd6dc218
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  22b3b10f-5736-4552-967a-4610bd6dc218:
    contentColumnType: text
    fieldGroup: null
    handle: quoteAttributionLabel
    instructions: ''
    name: 'Quote Attribution Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5a647dc5-6bc3-4530-8541-86caf15ef63a:
    contentColumnType: text
    fieldGroup: null
    handle: quoteAttribution
    instructions: ''
    name: 'Quote Attribution'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  8a4a9188-8dad-4ea2-beda-79dca5d5b7c5:
    contentColumnType: text
    fieldGroup: null
    handle: quoteText
    instructions: ''
    name: 'Quote Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: quoteBlock
name: 'Quote Block'
sortOrder: 8
