field: 6e341ae4-c396-4762-ab24-8a224c3933aa
fieldLayouts:
  a5a90d40-b94c-4c54-a8ef-63b424e13255:
    tabs:
      - fields:
          2b71de85-6440-4a9c-9493-ee62dd356f61:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  2b71de85-6440-4a9c-9493-ee62dd356f61:
    contentColumnType: text
    fieldGroup: null
    handle: classOverride
    instructions: ''
    name: 'Class Override'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: separator
name: Separator
sortOrder: 7
