field: 6e341ae4-c396-4762-ab24-8a224c3933aa
fieldLayouts:
  0858adf6-a017-4f8f-8733-5c92467dbe3d:
    tabs:
      - elements:
          - fieldUid: c6c4e479-3c72-445f-9be3-a2dcb4d51c06
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          - fieldUid: 199fd722-a993-4646-9f4a-8197dab58d53
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          - fieldUid: a8d57ba6-315d-4fa1-b09e-dc156635ffb0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  199fd722-a993-4646-9f4a-8197dab58d53:
    contentColumnType: text
    fieldGroup: null
    handle: tableCaption
    instructions: ''
    name: 'Table Caption'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a8d57ba6-315d-4fa1-b09e-dc156635ffb0:
    contentColumnType: string
    fieldGroup: null
    handle: alignment
    instructions: ''
    name: Alignment
    searchable: true
    settings:
      optgroups: true
      options:
        - __assoc__:
            - - label
              - Center
            - - value
              - aligncenter
            - - default
              - '1'
        - __assoc__:
            - - label
              - Left
            - - value
              - alignleft
            - - default
              - ''
        - __assoc__:
            - - label
              - Right
            - - value
              - alignright
            - - default
              - ''
        - __assoc__:
            - - label
              - 'Full Width'
            - - value
              - alignfull
            - - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c6c4e479-3c72-445f-9be3-a2dcb4d51c06:
    contentColumnType: text
    fieldGroup: null
    handle: table
    instructions: ''
    name: Table
    searchable: true
    settings:
      columnsAddRowLabel: 'Add Column'
      columnsInstructions: ''
      columnsLabel: Columns
      rowsAddRowLabel: 'Add Row'
      rowsInstructions: ''
      rowsLabel: Rows
    translationKeyFormat: null
    translationMethod: none
    type: supercool\tablemaker\fields\TableMakerField
handle: tableBlock
name: 'Table Block'
sortOrder: 11
