field: 6e341ae4-c396-4762-ab24-8a224c3933aa
fieldLayouts:
  80865030-5450-4b45-9dc0-d9a1f7dfb252:
    tabs:
      - elements:
          - fieldUid: 70ff1b83-9e35-4bf9-b9d9-8ff66f4f1b57
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          - fieldUid: 6a243f3c-db18-46fd-843e-5360d74421a6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6a243f3c-db18-46fd-843e-5360d74421a6:
    contentColumnType: boolean
    fieldGroup: null
    handle: dropcap
    instructions: ''
    name: Dropcap
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  70ff1b83-9e35-4bf9-b9d9-8ff66f4f1b57:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textBlock
name: 'Text Block'
sortOrder: 3
