fieldLayouts:
  67361467-b88c-4a31-a635-b6289c82ba47:
    tabs:
      - elements:
          - instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          - fieldUid: d36c166f-cd67-4185-9bc4-5ab1575f6fad
            required: true
            type: craft\fieldlayoutelements\CustomField
          - fieldUid: eb09c273-d05f-4c12-b325-c806f82ee9e2
            required: false
            type: craft\fieldlayoutelements\CustomField
          - fieldUid: 073a1223-abbb-47ba-8817-09bd9616aea7
            required: false
            type: craft\fieldlayoutelements\CustomField
          - fieldUid: 7385007b-d334-49bc-984a-123502b7b063
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Page Basics & Meta'
        sortOrder: 1
      - elements:
          - fieldUid: 865e9496-fa3d-4372-8697-33ebb0e2d03c
            required: false
            type: craft\fieldlayoutelements\CustomField
          - fieldUid: b9b564e6-850c-42bf-a84e-dc808c32a868
            required: false
            type: craft\fieldlayoutelements\CustomField
          - fieldUid: 01fc9a8c-9d56-41bb-82c7-44a9fb0bcbe1
            required: false
            type: craft\fieldlayoutelements\CustomField
          - fieldUid: b21ab3db-3b39-444f-ae0c-33c783266b56
            required: false
            type: craft\fieldlayoutelements\CustomField
          - fieldUid: d14e0870-385d-4950-b8f5-8d01434fae69
            required: false
            type: craft\fieldlayoutelements\CustomField
          - fieldUid: eaa8f6b6-38f7-4671-8f91-bebf5548e65d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Page Topper'
        sortOrder: 2
      - elements:
          - fieldUid: 6e341ae4-c396-4762-ab24-8a224c3933aa
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Page Content'
        sortOrder: 3
handle: pages
hasTitleField: true
name: Pages
section: db113630-fb48-4a20-bce0-896f4e7db46c
sortOrder: 1
titleFormat: ''
