contentColumnType: text
fieldGroup: 52be6dd4-059b-4710-a072-6b6820cca8be
handle: pageImageCaption
instructions: ''
name: 'Page Image Caption'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
