field: 844cedf4-3a01-4ded-9282-4a372923d162
fieldLayouts:
  256ed86d-6fe0-464a-8324-7062a40f8c62:
    tabs:
      - elements:
          - fieldUid: 1cfa6750-655f-4c56-a77b-cc3158ef3789
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          - fieldUid: d5b49bab-7b2b-4367-b874-9a1d8e17a36e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          - fieldUid: f0152f7f-c868-40e3-9fb8-f05acfc7b8b9
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1cfa6750-655f-4c56-a77b-cc3158ef3789:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d5b49bab-7b2b-4367-b874-9a1d8e17a36e:
    contentColumnType: string
    fieldGroup: null
    handle: buttonStyle
    instructions: ''
    name: 'Button Style'
    searchable: true
    settings:
      optgroups: true
      options:
        - __assoc__:
            - - label
              - Fill
            - - value
              - is-style-fill
            - - default
              - '1'
        - __assoc__:
            - - label
              - Outline
            - - value
              - is-styile-outline
            - - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f0152f7f-c868-40e3-9fb8-f05acfc7b8b9:
    contentColumnType: text
    fieldGroup: null
    handle: buttonLink
    instructions: ''
    name: 'Button Link'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
